platform :ios, '15.0'

target 'iosApp' do
  use_frameworks! :linkage => :static
  pod 'composeApp', :path => '../composeApp'
  pod 'FirebaseAuth', '10.29.0'
  pod 'FirebaseCore', '10.29.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f
      if current_target < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
